### ISSUE TITLE
Korali keeps running after error in model

### ISSUE THREAD

**Issue by cselab** [cselab/korali#285]
The setup which lead to the error can be found on Daint under `/users/pweber/CUP2Dkorali`. To reproduce the error, place a bug in `/users/pweber/CUP2Dkorali/model/runEvalCUP2D.py` and launch Korali via `sbatch /users/pweber/CUP2Dkorali/launchSbatch.sh`. You will observe that although using `sbatch -u username` you will still see the application running and allocating resources, when looking at the respective error file, you will see python's error-message.

**Comment by SergioMartin86** [comment]
Fixed.
