### ISSUE TITLE
cflags: wrong include path due to pybind11

### ISSUE THREAD

**Issue by amlucas** [cselab/korali#344]
```
python3 -m korali.cxx --cflags
```
gives me one include path which is wrong.
I traced it back to pybind11:
```
> python3 -m pybind11 --includes
-I/opt/python/3.7.2/include/python3.7m -I/home/amlucas/.local/include/python3.7m
```
the second path does not exist for me.
This is in general not a big problem, but as I pass it through cmake there is a complain that this path does not exist.

**Comment by SergioMartin86** [comment]
This is solved by meson
