### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by sunsibar** [cselab/korali#348]
On the cluster, installing and running Korali works without problems, but not locally. I can run the C++ example without problems (ex. C1), but all Python examples fail.
 @wadaniel has seen the problem already. To have it documented, this is what happens:

```
python3 --version
>> Python 3.6.9
gcc --version
>> gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
pip3 uninstall korali
rm -rf korali/
git clone git@github.com:cselab/korali.git
cd korali/

sudo apt-get install python python3 python-dev python3-dev
pip3 freeze | grep pybind
>> pybind==0.1.35
>> pybind11==2.4.3
gsl-config --version
>> 1.16

./install
[... Finished installing successfully]

cd tutorials/a1-optimization
python3 -m run-cmaes.py
>> Segmentation fault (core dumped)
```

When running it in PyCharm:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/noobuntu/.local/lib/python3.6/site-packages/korali/libkorali.so: undefined symbol: gsl_multimin_fminimizer_nmsimplex
```
(The line that throws the error is “from libkorali import Engine, in \_\_init\_\_.py.)

On the other hand, 
```
cd ../c1-[tab]
make
./run-cmaes
[...]
[Korali] Optimizer/CMAES finished correctly.
[...]
```
This works perfectly fine.

**Comment by misteliy** [comment]
I had a similar issue which was connected to the interplay of the different components. However, I managed to get everything ruining within that dockerfile:

FROM python:3.8-slim-buster

RUN apt-get update 

RUN apt-get install -y build-essential python3 python3-dev \
    python3-pip python3-venv python3-pybind11 pybind11-dev

RUN apt-get install -y git wget vim cmake

RUN apt-get install -y libgsl-dev

# update pip
RUN python3 -m pip install pip --upgrade
RUN python3 -m pip install wheel pandas scipy requests pybind11

RUN git clone https://github.com/cselab/korali.git --branch latest

RUN cd korali && ./install --no-prereqs
