### ISSUE TITLE
Tutorial a9-surrogate fails

### ISSUE THREAD

**Issue by sunsibar** [cselab/korali#349]
@wadaniel , and not urgent, has time till in two weeks +.

When trying to run [a9](https://github.com/cselab/korali/tree/master/tutorials/a9-surrogate), I got an error at the second stage. It seems like the first stage should write final results to a file called "_korali_result_train/final.json", which it doesn't do. The error message is: 

```
[...  output from the first experiment ]
[Korali] --------------------------------------------------------------------
[Korali] Optimizer/Rprop finished correctly.
[Korali] Termination Criterion Met: Rprop['Max Stall Generations'] = 20.
[Korali] Final Generation: 97
[Korali] Elapsed Time: 0.010s
[Korali] Error: Could not load Gaussian Process Json file.
Aborted
```
The first experiment (training the Gaussian process) runs fine. Afterwards, the output folder "_korali_result_train/" contains two files: `gen00000000.json` and  `gen00000097.json`. 
No `final.json`. 

Looking at the code, korali::Experiment::saveState() in `source/experiment/experiment.cpp`  seems to be the function that should create `final.json`:

```
  // Saving last generation and final.json
  _currentGeneration--;
  _isFinished = true;
  saveState();
```
But saveState() doesn't name the file "final.json".

If I change the "Gaussian Process Json File" of the second experiment to the `gen00000097.json` file, experiment 2 runs fine. But the configuration for experiment 3 seems to have some problems as well.

Ideas?

**Comment by SergioMartin86** [comment]
GP examples work now
