### ISSUE TITLE
variable module

### ISSUE THREAD

**Issue by wadaniel** [cselab/korali#357]
for me, variables belong into the modules folder. lets review this.
for following reasons:

"also if you look at the description of a korali app you would assume they are on the same level, also we present them in the paper as a module."
"variable’ and ‘distribution’ have an equal abstraction level for me, and hence variable belongs into the modules folder. One could argue that distributoins are ingredients for variables, and hence variable has a greater prio, thatswhy variable is not in modules but on its own"

lets review this.

**Comment by SergioMartin86** [comment]
it's not a module, it's a implementation issue
