### ISSUE TITLE
SAEM tests

### ISSUE THREAD

**Issue by wadaniel** [cselab/korali#362]
Hi Susanne,
may you add some 'statistical' tests in /tests/STAT-004/ for SAEM?
there are sampling tests for MCMC, TMCMC and Im currently adding tests for my new sampler, and I found there are no tests for SAEM.

If this makes sense, otherwise we come up with other tests that check the statistical properties. Happy to discuss.

**Comment by SergioMartin86** [comment]
SAEM is no longer a module in Korali
