### ISSUE TITLE
Use CMAKE for Korali's installation 

### ISSUE THREAD

**Issue by SergioMartin86** [cselab/korali#374]
-	It would make it easier to link korali with apps
-	You can use Pkg-config to get flags
-	Supposed to be cross-platform
-	Still compatible with install.sh?

**Comment by ikicic** [comment]
Cmake would also make detecting MPI much easier. Now the user has to manually specify MPICXX to compile with MPI.

**Comment by SergioMartin86** [comment]
We decided for Meson, which seems to be better
