### ISSUE TITLE
korali hangs

### ISSUE THREAD

**Issue by wadaniel** [cselab/korali#402]
Hi Sergio,

Petr observed that korali (TMCMC) is hanging after installing a version later than thisone:
https://github.com/cselab/korali/commit/75d528365d66edcd9b7b8decd0602165336ec8f3
do you have an idea? Petr, can you clarify a bit where it is hanging? or what you observe? where and when?
Thanks,
Daniel

**Comment by ikicic** [comment]
1 < 24 should be probably 1 << 24

**Comment by divfree** [comment]
checked again in current master,
no longer hangs
