### ISSUE TITLE
Use single-precision representation

### ISSUE THREAD

**Issue by SergioMartin86** [cselab/korali#414]
Idea: since we are dealing with approximations, it may not be necessary to represent numbers to such a computational precision. Especially when talking about DNNs.

Pros? Cons? Have it as configuration variable?

**Comment by webepasc** [comment]
It should be there as a configuration variable for sure. I would even go that far, that the user should know/decided whether for his problem single precision is suited. On our side, we should consider the impact of using high precision on the performance and report this correspondingly. On this site https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html it is said that oneDNN is optimized for fp32, so I guess this should be the standard-setting. However this only regards the supported hardware, I have no idea how this looks like when running the inference/training on the GPU (where we might want to use the advantage of tensor-cores: https://www.nvidia.com/en-gb/data-center/tensor-cores/)

**Comment by amlucas** [comment]
You can use something like this 
```
namespace korali {
#ifdef KORALI_SINGLE_PREC
using real = float;
#else
using real = double;
#endif

inline namespace literals {

constexpr inline real operator"" _r(const long double a) { return (real)a; }

}  // namespace literals
} // namespace korali
```

**Comment by ikicic** [comment]
The `real` alias seems like a best choice if you are thinking about changing between single and double precision. It is a non-breaking change (you have to set `double` as default), and people can still experiment with single precision if they want.
Regarding NNs, I'd say it's unrelated to the rest of Korali. It's like saying that Korali should be single-precision because Mirheo it is running is single-precision.

**Comment by amlucas** [comment]
On top of what @ikicic mentioned: There could be a `realNN` specific to the NN part, that could be configurable also at compile time.
That way you can still have double precision where it matters and keep single (or even half?) precision for the NNs.
I did this in Mirheo: default is float everywhere (DPD doesn't need double) but the computation of the forces of the membranes is performed in double precision.
Both are configurable at compile time and I have tests for both single and double precision..

**Comment by SergioMartin86** [comment]
Done for NN
