### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by ikicic** [cselab/korali#417]
https://github.com/cselab/korali/blob/master/source/modules/problem/gaussian/evaluate/evaluate._cpp#L18

The _variables does not seem to be properly cleaned up. Grepping for "delete" and "_variables" does not find any nearby matches within +-10 lines.

Are pointers even needed here? If so, would std::unique_ptr work here?

**Comment by gtarabat** [comment]
We will move to unique pointers. Duplicate of #462
