### ISSUE TITLE
`--prereqs` option downloads git repositories

### ISSUE THREAD

**Issue by fab4100** [cselab/korali#450]
For the dependencies actual git repositories are downloaded and then a specific
version is checked out.  This is wasteful because you download over 100MB of
useless git history in that repo.  Instead, download the actual release version
of the dependency (tarball under the releases tab in gitlab or github).

**Comment by ikicic** [comment]
you can also pass --depth=1 to git clone, as a quick (partial) solution

**Comment by fab4100** [comment]
This hack will not work.  It may strip off your git history and reduce the
download volume but it removes all tags leaving you always on master for the
third party dependency.  If korali generates releases, those depend on the
current (the here and now) state of the third party, that is the current
third party version that works with the current korali release must be used.  
If your dependency management in korali always follows the master branch of
your dependencies, if one of those dependencies decides to change its API in
the future (I am allowed to do this on master) ALL your korali releases of the
previous time will be broken.

**Comment by ikicic** [comment]
you can clone to a tag, not a master. but, yes, it is easier to download tarballs.
