### ISSUE TITLE
documentation internal states

### ISSUE THREAD

**Issue by wadaniel** [cselab/korali#494]
Hi,

I have been asked about the meaning of the internal states, and now I see our documentation doesn't show it: e.g.
https://www.cse-lab.ethz.ch/korali/docs/modules/solver/optimizer/CMAES/CMAES.html

would it be possible to add the internal states also to our documentation page?

**Comment by gtarabat** [comment]
Internal variables documentation is created by doxygen and is located under code documentation. Fixed.
