### ISSUE TITLE
Unused computation in MOCMAES, possible bug

### ISSUE THREAD

**Issue by gtarabat** [cselab/korali#552]
In the file `MOCMAES._cpp` the [following computation](https://github.com/cselab/korali/blob/741b89333144794d149f5d4349ba420ba069cf2f/source/modules/solver/optimizer/MOCMAES/MOCMAES._cpp#L351) is unused

```
if (sortedIndices[i] >= (int)(values.size() - _muValue)) _currentSuccessProbabilities[i] + _successLearningRate;
```

Does it meant to be
```
if (sortedIndices[i] >= (int)(values.size() - _muValue)) _currentSuccessProbabilities[i] += _successLearningRate;
```
?

**Comment by wadaniel** [comment]
yes, thanks, Ill fix it
