### ISSUE TITLE
Possible bug in nested sampling

### ISSUE THREAD

**Issue by gtarabat** [cselab/korali#560]
Why do you check only for `dim==2` in [this line](https://github.com/cselab/korali/blob/49cf53b82a59be254a6ef11c1c5c2fddc79166a3/source/modules/solver/sampler/Nested/Nested._cpp#L99)?

Shouldn't it be `dim<3`?

In addition, if the default resampling method doesn't work, add in the error message which resampling methods work in this case.

**Comment by wadaniel** [comment]
true, you are correct, thanks for finding it. Ill fix it
