### ISSUE TITLE
Index out of bounds in HMC_implementation

### ISSUE THREAD

**Issue by pfuxs** [cselab/korali#562]
In File [Bayesian._cpp](https://github.com/cselab/korali/blob/HMC_implementation/source/modules/problem/bayesian/bayesian._cpp) line 106:

`size_t numParam = logPriorHessian.size();`
 ` for (size_t i = 0; i < numParam; i++)`
    `logLikHessian[i * numParam + i] += logPriorHessian[i * numParam + i];`

But logPriorHessian is a _numParam * numParam_ matrix (line 50):

`std::vector<double> logPriorHessian(numParam * numParam, 0.);`

**Comment by wadaniel** [comment]
thank you for finding the bug and creating this issue. I fixed the problem and pushed the code to this branch
