### ISSUE TITLE
automatic installation of eigen fails

### ISSUE THREAD

**Issue by ikicic** [cselab/korali#581]
`meson setup build` fails with the following error

```
  (...)
  File "/home/kicici/.local/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 399, in get_file
    shutil.unpack_archive(path, extract_dir)
  File "/opt/python/3.7.2/lib/python3.7/shutil.py", line 995, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format '/home/kicici/code/korali/subprojects/packagecache/eigen-3.3.9.tar.bz2'
```

Ubuntu
Python version 3.7.2
Meson version 0.58.0

Am I missing some dependency?

**Comment by ikicic** [comment]
It seems like Python 3.8+ is required.

Maybe update the docs and README? The docs currently says that "Korali requires a version of Python higher than 3.0 to be installed in the system.".

**Comment by gtarabat** [comment]
Python 3.8 is the minimum version. Put in the requirements.
