### ISSUE TITLE
Truncated Normal LogDensity producing wrong results

### ISSUE THREAD

**Issue by SergioMartin86** [cselab/korali#586]
https://github.com/cselab/korali/blob/d11739ba16cd07139e3c89e12f3b05bb529ec562/source/modules/distribution/univariate/truncatedNormal/truncatedNormal._cpp#L21

produces different results than running simply

 return std::log(getDensity(x));

Same for the Weibull distribution 

https://github.com/cselab/korali/blob/d11739ba16cd07139e3c89e12f3b05bb529ec562/source/modules/distribution/univariate/weibull/weibull._cpp#L15

please check

**Comment by wadaniel** [comment]
I take the issue and fix it on my branch nested-cleanup for which I create a PR soon

**Comment by wadaniel** [comment]
fixed in here, need to test: https://github.com/cselab/korali/commit/bbd81d3faa446a67d64ff80aa9e1c93702d68d18
